spring:
  spring:
    application: name=event-driven-arch
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
        acknowledge-mode: auto
    template:
      mandatory: true